@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk0MTU2MDB9.zt1Qsf1heDiw5ArwpVmozt_zrvlkPhMcMLMS6grHUog",

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Tester",
  "email": "tester@tester.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "tester@tester.com",
  "password": "password"
}

### Services create
POST http://localhost:3000/services.json
Content-Type: application/json

{
  "name": "Hulu-test",
  "region": "US",
  "source_id": 157
}

### create join-table connection between user and their services
POST http://localhost:3000/service_users.json
Content-Type: application/json

{
  "user_id": 1,
  "service_id": 2
}

### test-choices
GET http://localhost:3000/choices.json